%% foil_gen
% generate initial configuration and final target of the morphing airfoil
clc;clear all; close all;
load('member_info.mat'); % this is generated by Main_foil_kinematics.m
load('Ntrace.mat'); % this is generated by Main_foil_kinematics.m
foil_str = '2412'; propu = min(N(1,2:end)); propl = 1;
for i=1:length(N(1,:))
    if N(2,i)<0
        propl = min(propl,N(1,i));
    end
end
[xU,xL,zU,zL] = gene_airfoil_front(foil_str,propu,propl);
x_front = [xU;xL]; z_front =[zU;zL];
%%
[xU2,xL2,zU2,zL2] = gene_airfoil_front(foil_str,1,1);
x_front2 = [xU2;xL2]; z_front2 =[zU2;zL2];
%%
[N_cell,N0,CBT,CST] = Main_foil_bend();
%%
figure(1)
% xlim([0 1]);ylim([-0.2 0.2]);
% xlabel('Chrod X (m)','Interpreter','latex')
% ylabel('Y (m)','Interpreter','latex'); hold on
% set(gca,'fontsize', 12,'linewidth',1.15);
% set(gca,'ticklength',1.2*get(gca,'ticklength'));hold on

% f1 = plot(x_front,z_front,'r-',x_front2,z_front2,'b--','linewidth',1); hold on;
% % f2 = plot(x_front2,z_front2,'b--','linewidth',1); legend('Discrete Shape'); hold on;
% ah = legend('Continous Shape','Discrete Shape');
% legend off;
% ah = legend([f1 f2],'Continous Shape','Discrete Shape')
% l1=legend(f1,'Continous Shape');
% set(l1,'units','normalized');
% l2=legend(f2,'Discrete Shape');
% set(l2,'units','normalized');
% legend('Continous Shape','Discrete Shape')
fill(x_front,z_front,[25/255 25/255 112/255]); hold on
tenseg_plot(N0,CBT,CST,1); grid on; hold on;
xlim([0 1]);ylim([-0.15 0.15]);
xlabel('Chrod X (m)','Interpreter','latex')
ylabel('Y (m)','Interpreter','latex')
set(gca,'fontsize', 12,'linewidth',1.15);
set(gca,'ticklength',1.2*get(gca,'ticklength'));
%
N_simple = N; pinned_nodes = [1 7 12]; C_b=CBT; C_s=CST;
[N_new,Cb,Cs,P,~] = tenseg_class_k_convert(N_simple,C_b,C_s,pinned_nodes);
tenseg_plot_target_3D(Ntrace(:,:,end),Cb,Cs,N_cell{1,end}',1);
xlim([0 1]);ylim([-0.15 0.15]);
xlabel('Chrod X (m)','Interpreter','latex')
ylabel('Y (m)','Interpreter','latex')
% set(gca,'fontsize', 12,'linewidth',1.15);
% set(gca,'ticklength',1.2*get(gca,'ticklength'));hold on
f1 = plot(x_front,z_front,'r-',x_front2,z_front2,'b--','linewidth',1); hold on;
% f2 = plot(x_front2,z_front2,'b--','linewidth',1); legend('Discrete Shape'); hold on;
ah = legend([f1(1),f1(2)],'Discrete Shape','Continous Shape','location','SouthEast');